#!/bin/python3

import sys
import socket
from datetime import datetime

#def target
if len(sys.argv) == 2:
	target = socket.gethostbyname(sys.argv[1]) #translate hostname to ipv4
else:
	print("invalid amount of arguments.")
	print("Syntax: Python3 scanner.py <ip>")


#Add a pretty banner
print("_" * 50)
print("Portscanner creator: Javis Wahome")
print("Scanning target: " + target)
print("Time started: "+str(datetime.now()))
print("_" * 50)

try:
	for port in range(1,99999):
		s = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
		socket.setdefaulttimeout(1)
		result = s.connect_ex((target,port)) #returns an error indicator
	
		#print("checking port {}".format(port))
		if result == 0:
			print("port {} is open".format(port))
		s.close()

except KeyboardInterrupt:
	print("\nExiting program.")
	sys.exit()

except socket.gaierror:
	print("Hostname could not be resolved.")
	sys.exit()

except socket.error:
	print("Couldn't connect to server.")
	sys.exit()

